language: java

jdk:
  - oraclejdk8
sudo: false
install: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: mvn test

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - sed -i -e "s?--BUILD-VERSION--?$GIT_TAG?g" src/main/resources/application.yml
  - git commit -m "Set build VERSION number as $GIT_TAG" src/main/resources/application.yml
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUBKEY@github.com/empowerhack/hub $GIT_TAG > /dev/null 2>&1
